### PR TITLE
[DNM] Hold split modifications / improvements

### PR DESCRIPTION
**Pull request by Timo614**
Requires big-neon/bn-web#1192

### Closes Issues:
Closes: #1065

### Description:
The associated issue was about how children holds of a hold always had Comp hold types. It was referring to the list feature when you select a hold in the bn-web tooling. That feature worked by using the Comps endpoints. Historically we only allowed Comps as children of other holds. This branch changes this.

@Jasonvdb I think this should work as a replacement for the logic the hold list dialog is using now (comps index and create currently). The split endpoint can be used to create children of a given hold and there is now a new endpoint that lists all children whether comp or hold.

Changes:
- I added the additional comp fields (phone, email) to the split endpoint as optional fields.
- Split now has the option of passing in whether the resulting split should be a child of the hold or inherit its parent. Passing nothing for this field defaults to inheriting from the parent so existing split behavior should still function.
- Added a new children endpoint which lists all of the child holds ordered by hold type, hold name

Note:
- Currently keeping the comps endpoints around to avoid breaking any existing callers. We can keep using them if we want but you can achieve the same behavior with the split logic now set to Comp and to be a child of the existing hold.
- Not forcing children of a type to be the same as their parents. We could do this if desired though.

Examples:

Calling split without the optional `child` boolean parameter resulting in a normal split:
```
curl --header "Content-Type: application/json" --request POST --data '{"name": "New split", "redemption_code": "XYZABC123", "hold_type": "Discount", "quantity": 1, "discount_in_cents": 10}' http://localhost:9000/holds/ef4387b3-e82a-4ea5-812a-31836b227043/split --header "Authorization: Bearer ..."

{  
   "id":"882dbd65-9dc8-421f-83c4-0057937ab49f",
   "name":"New split",
   "parent_hold_id":null,
   "event_id":"705c543b-6973-406d-8f51-3eb0dc95a040",
   "redemption_code":"XYZABC123",
   "discount_in_cents":10,
   "end_at":null,
   "max_per_order":null,
   "hold_type":"Discount",
   "ticket_type_id":"4b3bc8b9-6a0a-472f-8a91-e7edaa733ae8",
   "email":null,
   "phone":null,
   "created_at":"2019-02-28T21:41:09.137452",
   "updated_at":"2019-02-28T21:41:09.137452"
}
```

Calling split with the optional `child` boolean parameter resulting in a child hold of the specified split parent:
```
curl --header "Content-Type: application/json" --request POST --data '{"name": "New split2", "redemption_code": "XYZABC1234", "hold_type": "Discount", "quantity": 1, "discount_in_cents": 10, "child": true}' http://localhost:9000/holds/ef4387b3-e82a-4ea5-812a-31836b227043/split --header "Authorization: Bearer ..."

{  
   "id":"a7d82ecb-4752-4f0b-8c81-4bd2cc7ab78f",
   "name":"New split2",
   "parent_hold_id":"ef4387b3-e82a-4ea5-812a-31836b227043",
   "event_id":"705c543b-6973-406d-8f51-3eb0dc95a040",
   "redemption_code":"XYZABC1234",
   "discount_in_cents":10,
   "end_at":null,
   "max_per_order":null,
   "hold_type":"Discount",
   "ticket_type_id":"4b3bc8b9-6a0a-472f-8a91-e7edaa733ae8",
   "email":null,
   "phone":null,
   "created_at":"2019-02-28T21:41:37.012957",
   "updated_at":"2019-02-28T21:41:37.012957"
}
```

Adding a Comp as well:
```
curl --header "Content-Type: application/json" --request POST --data '{"name": "New split3", "redemption_code": "XYZABC12345", "hold_type": "Comp", "quantity": 1, "child": true}' http://localhost:9000/holds/ef4387b3-e82a-4ea5-812a-31836b227043/split --header "Authorization: Bearer ..."

{  
   "id":"b0b0bf61-b04e-48c7-bbe9-698fff66b949",
   "name":"New split3",
   "parent_hold_id":"ef4387b3-e82a-4ea5-812a-31836b227043",
   "event_id":"705c543b-6973-406d-8f51-3eb0dc95a040",
   "redemption_code":"XYZABC12345",
   "discount_in_cents":null,
   "end_at":null,
   "max_per_order":null,
   "hold_type":"Comp",
   "ticket_type_id":"4b3bc8b9-6a0a-472f-8a91-e7edaa733ae8",
   "email":null,
   "phone":null,
   "created_at":"2019-02-28T21:42:30.025574",
   "updated_at":"2019-02-28T21:42:30.025574"
}
```

Calling for all the children of a hold (with various `Comp` and `Discount` children):
```
curl http://localhost:9000/holds/ef4387b3-e82a-4ea5-812a-31836b227043/children --header "Authorization: Bearer ..."

{  
   "data":[  
      {  
         "id":"b0b0bf61-b04e-48c7-bbe9-698fff66b949",
         "parent_hold_id":"ef4387b3-e82a-4ea5-812a-31836b227043",
         "hold_type":"Comp",
         "name":"New split3",
         "event_id":"705c543b-6973-406d-8f51-3eb0dc95a040",
         "redemption_code":"XYZABC12345",
         "discount_in_cents":null,
         "max_per_order":null,
         "email":null,
         "phone":null,
         "available":1,
         "quantity":1
      },
      {  
         "id":"a7d82ecb-4752-4f0b-8c81-4bd2cc7ab78f",
         "parent_hold_id":"ef4387b3-e82a-4ea5-812a-31836b227043",
         "hold_type":"Discount",
         "name":"New split2",
         "event_id":"705c543b-6973-406d-8f51-3eb0dc95a040",
         "redemption_code":"XYZABC1234",
         "discount_in_cents":10,
         "max_per_order":null,
         "email":null,
         "phone":null,
         "available":1,
         "quantity":1
      }
   ],
   "paging":{  
      "page":0,
      "limit":100,
      "sort":"",
      "dir":"Asc",
      "total":2,
      "tags":{  

      }
   }
}
```

## Release Details:
Changes should be backwards compatible as only modifications were optional additional fields on the split endpoint. The postman tests were not modified (I added unit and functional tests so we have coverage of the new feature) so it shows the existing split test also continues to pass.

### Migrations
 * No Migrations

### Environment Variables
 * No change

### CODE REVIEW

**Comment by Timo614** [comment]
Going to hold off on rebasing this / fixing conflicts for the time being. Let me know if we still want this functionality and if so will get it back up to date and retest.

**Comment by Timo614** [comment]
@Jasonvdb should be set -- I reran the tests and tried it locally and the split logic looks good. 

One thing I did notice was the children appear in the main holds listing in my branch right now. Do we want to filter out any child from the main listing? Right now you could make multiple levels of children as you split a hold down. We could just show only the parents on the listing or provide a querystring argument to filter in that way if that's ideal.

**Comment by Jasonvdb** [comment]
Thanks @Timo614 I think let's leave the listing changes for now until @zmelamed gives feedback there

**Comment by Krakaw** [comment]
This should go in on Tuesday.

**Pull request merged**
