### PR TITLE
Sw return org roles in org users request

### PR DESCRIPTION
**Pull request by SWvheerden**
this allows the web to see roles assigned to a user
#702

### CODE REVIEW

**Comment by Jasonvdb** [comment]
@SWvheerden does this return the org lever roles? OrgOwner/OrgMember/OrgBoxOffice/OrgScanner

**Comment by SWvheerden** [comment]
It should return these:
string_enum! { Roles [Admin, OrgMember, OrgOwner, OrgBoxOffice, OrgScanner, User] }

**Comment by Jasonvdb** [comment]
Don't you need `users.get_roles_by_organization()` for that?

**Comment by SWvheerden** [comment]
Not as far as I can pickup

**Pull request closed without merging**
