### PR TITLE
WIP: Complimentary tickets

### PR DESCRIPTION
**Pull request by Timo614**
Closes: #422 

WIP, will add more later. I left a note in the associated issue but handling this by marking a subset of tickets as complimentary and then allowing those to be transferred by any organization member with the ComplimentaryTransfer scope. Still need to add tests and make sure there aren't any areas I've missed with the logic. May end up adjusting this further as well flow wise depending upon if the direction I was going here is incorrect (clarifying via 422).

### CODE REVIEW

**Comment by mikethetike** [comment]
I added some comments to #422. I don't know why wafflebot assigned me to this though...

**Comment by Timo614** [comment]
@mikethetike waiting for Zach's comments before I touch this further to get clarification there on the flow (and also working on other responsibilities at the moment so won't be able to work on bigneon for at least another day) but can switch it to whatever flow we think is best.

That's fine switching it to use a Comp wallet instead and using an order. I hadn't released we wanted to have an order for these and the associated issues were a bit light on details so went with the direction of making it a new ticket type status versus purchased as these weren't 'Purchased' per se.

Once the associated issue is updated with whatever the business team thinks is best will circle back and adjust to use an order instead.

**Comment by mikethetike** [comment]
> a bit light on details

:joy: yip

**Comment by Timo614** [comment]
Reviewing the associated issue and flow Zach mentioned. Going to close this PR and make a new branch and PR for the changes mentioned there as it's hold based so this logic won't be useful for it.

**Pull request closed without merging**
